# Generated by Django 4.1 on 2022-08-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0002_account_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
